- hosts: web
  user: desktop
  become: yes
  gather_facts: yes
  vars_files:
    - ../vars_files/vars.yml
  tasks:
    - name: create applications_root
      file:
        path: "{{ applications_root }}"
        state: directory
        owner: apache
        group: apache
        mode: 0770
