- hosts: db
  gather_facts: no
  become: true
  user: test
  vars_files:
    - ../vars_files/vars.yml
  tasks:
    - name: install yum repository
      yum:
        name: "{{ postgresql_repo }}"
    
    - name: install postgresql
      yum: name={{ item }}
      with_items:
        - postgresql{{ postgresql_version_except_dot }}-devel
        - postgresql{{ postgresql_version_except_dot }}-libs
        - postgresql{{ postgresql_version_except_dot }}-server
        # - python-psycopg2 # ansibleでdb設定するのであれば必要

    - name: init db
      shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version_except_dot }}-setup initdb"
      args:
        creates: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf

    - name: regist systemd
      systemd:
         name: postgresql-{{ postgresql_version }}
         state: restarted
         daemon_reload: yes
