- hosts: ap
  user: desktop
  gather_facts: yes
  vars_files:
    - ../vars_files/vars.yml
  tasks:
    - name: install dependency library
      become: true
      yum: name={{ item }}
      with_items:
        - git
        - bzip2
        - gcc
        - gcc-c++
        - openssl-devel
        - readline-devel
        - zlib-devel
        - make

    - name: clone rbenv
      become: true
      git:
        repo: https://github.com/sstephenson/rbenv.git
        dest: "{{ rbenv_home }}/.rbenv"

    - name: generate rbenv.sh and deploy
      become: true
      template:
        src: rbenv.sh.tj2
        dest: /etc/profile.d/rbenv.sh

    - name: source rbenv.sh
      become: true
      shell: source /etc/profile.d/rbenv.sh

    - name: clone rbenv-build
      become: true
      git: 
        repo: https://github.com/sstephenson/ruby-build.git
        dest: "{{ rbenv_home }}/.rbenv/plugins/ruby-build"

