# https://owani.net/ruby_on_rails/apache-passenger/414/
- hosts: web
  gather_facts: no
  become: true
  become_method: su
  vars_files:
    - ../vars_files/postgresql.yml
  tasks:
    - name: install httpd
      yum:
        name: httpd-{{ httpd_version}}
        state: latest

    - name: start service
      systemd:
        name: httpd
        state: restarted

    - name: open 80 port firewall
      command: firewall-cmd --permanent --add-port=80/tcp
      notify: restart firewalld

    - name: restart firewalld
      systemd:
        name: firewalld
        state: restarted
        daemon_reload: yes
        enabled: yes
